---
- name: get current xs host uuid
  shell: cat /etc/xensource-inventory | grep -iPo "(?<=installation_uuid=).*"
  register: host_uuid_res
  
- set_fact:
    host_uuid: "{{ host_uuid_res.stdout | replace(\"'\", '')  }}"

- name: install packages
  yum: name={{ item }} state=present enablerepo=base-rbdsr,updates-rbdsr,extras-rbdsr,centosplus-rbdsr
  with_items:
    - epel-release
    - yum-plugin-priorities.noarch
    - snappy
    - leveldb
    - gdisk
    - python-argparse
    - gperftools-libs

- name: configure waitdmmerging
  action: copy src={{ rbdsr_file_source_dir }}waitdmmerging.sh dest=/usr/bin/waitdmmerging.sh owner=root group=root mode=755

- name: configure xs plugin
  action: copy src={{ rbdsr_file_source_dir }}{{ item }} dest=/opt/xensource/sm owner=root group=root
  with_items:
    - RBDSR.py
    - cephutils.py

- name: compile xs plugin
  command: python -m compileall {{ item }} && python -O -m compileall {{ item }} 
  args:
    chdir: /opt/xensource/sm
  with_items:
    - RBDSR.py
    - cephutils.py

- name: create RBDSR symlink    
  file: src=/opt/xensource/sm/RBDSR.py dest=/opt/xensource/sm/RBDSR state=link
  
- name: allow rbd SM plugin
  lineinfile: dest=/etc/xapi.conf regexp='^sm-plugins= (?!rbd)(.*)' line='sm-plugins= rbd \1' backrefs=yes
  notify: restart xe-toolstack


## prepare the SR within XenServer
- name: check if sr exists
  command: xe sr-list uuid={{ xen_sr_uuid }} --minimal
  register: sr_exists

- name: add sr to xenserver
  command: xe sr-introduce name-label="CEPH RBD Storage" type=rbd uuid={{ xen_sr_uuid }} shared=true content-type=user
  when: not sr_exists.stdout


- name: check if pbd exists
  command: xe pbd-list host-uuid={{ host_uuid }} sr-uuid={{ xen_sr_uuid }} --minimal
  register: pbd_exists

- name: create pbd in host
  command: xe pbd-create sr-uuid={{ xen_sr_uuid }} host-uuid={{ host_uuid }}
  when: not pbd_exists.stdout
  register: pbd_exists

- name: plug pbd in host
  command: xe pbd-plug uuid={{ pbd_exists.stdout }}
  when: pbd_exists.stdout
